[features]
seeds = false
skip-lint = false
[programs.devnet]
clamespl = "EqC6pAzi3nkGvx7jwXQ6mhLjHR8YGUwWvAqG8fFkFy5y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/monish/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
